---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: cluster4
  region: us-east-1
availabilityZones: 
- us-east-1a
- us-east-1b
managedNodeGroups:
- name: on-demand
  labels:
    role: on-demand
  instanceType: t3.medium
  desiredCapacity: 2
  volumeSize: 20
